apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1  # Set the number of replicas based on your requirement
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/<repository-name>:<tag> 
        imagePullPolicy: Always  
        ports:
        - containerPort: 80  
