apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: 585768173504.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
          ports:
            - containerPort: 80
