---
- name: Install and configure NGINX
  hosts: localhost
  become: true       
  tasks:
    - name: login to ecr
      command: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 585768173504.dkr.ecr.ap-south-1.amazonaws.com
        
