---
- name: List all S3 Buckets
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml  # Include the vars.yml file
  tasks:
    - name: List all S3 Buckets
      community.aws.s3_bucket_facts:
        region: "{{ aws-region }}"
        aws-access-key: "{{ aws-access-key }}"
        aws_secret_key: "{{ aws-secret-key }}"
      register: s3_buckets
