name: Remote Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Using SSH
        run: ssh -o StrictHostKeyChecking=no ubuntu@3.109.55.13 "touch /opt/newfile.txt" 
