name: Remote Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan 
 
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: login to ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: push image
        run: | 
          docker build -t nginx .
          docker tag nginx:latest 585768173504.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
          docker push 585768173504.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
      - name: eks configure
        run: aws eks update-kubeconfig --name my-eks-cluster --region ap-south-1

      - name: create pod
        run: kubectl apply -f deployment.yml

      - name: list nodes  
        run: kubectl get nodes 

      - name: list pods
        run: kubectl get pods
        

    
