name: Remote Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  

      - name: publicips
        run: |
           REGION="us-east-1"

              
           PUBLIC_IPS=$(aws ec2 describe-instances \
           --region "$REGION" \
           --query "Reservations[*].Instances[*].PublicIpAddress" \
           --output text)
           echo "$PUBLIC_IPS"
      

          
      
      

      
        
