name: aws

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: "ap-south-1"

      - name: Verify AWS CLI installation
        run: aws --version
          

