name: Terraform CI/CD

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
       
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}


      - name: Set up AWS CLI
        run: |
          # Update and install dependencies
          sudo apt-get update
          sudo apt-get install -y unzip

          # Download AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

          # Unzip the installer
          unzip awscliv2.zip

          # Run the AWS CLI installer
          sudo ./aws/install

      - name: Verify AWS CLI installation
        run: aws --version
          

