name: Second Workflow

on:
  workflow_run:
    workflows: ["Terraform CI/CD"] 
    types:
      - completed
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
     
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: "ap-south-1"

      - name: Verify AWS CLI installation
        run: chmod 777 ./aws.sh

      - name: Verify AWS CLI installation
        run: ./aws.sh
          

