name: CI Pipeline

# Trigger the workflow on push or pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for the workflow
jobs:
  build:
    # The job will run on the latest Ubuntu image
    runs-on: ubuntu-latest

    # Steps to be executed within the job
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    
