name: Remote Deployment

on:  
  push:     
    branches: 
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.3.7"  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up environment to disable SSH host key checking
        run: echo "ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV
      

      - name: login
        run: ansible-playbook -i hosts ecr.yml
      

      

      

        


      

      
        

        

        

      
