name: Remote Deployment

on: 
  push:     
    branches: 
      - main
env:
 Region: us-east-1
 name: nginx
 clustername: my-eks-cluster 

jobs:  
  terraform:
    runs-on: ubuntu-latest 
    
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.3.7"  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ env.Region }} 

      - name: repo check
        run: |

           repos=($(aws ecr describe-repositories --region "$Region" --query "repositories[*].repositoryName" --output text))
           for repose in "${repos[@]}; do
 
           if [ "$repo" == "nginx" ]; then
       
           echo "nginx repo already exists"

           break
           else

           aws ecr create-repository --repository-name ${{ env.name }}  --region ${{ env.Region }}  
   
           fi

           done    
      
          
     
      

      

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: create ecr repo
        run: aws ecr create-repository --repository-name ${{ env.name }}  --region ${{ env.Region }} 
        continue-on-error: true  

      - name: build docker image
        run: docker build -t nginx .

      - name: docker tage
        run: docker tag nginx:latest 585768173504.dkr.ecr.${{ env.Region }}.amazonaws.com/${{ env.name }}:latest

      - name: push to ecr
        run: docker push 585768173504.dkr.ecr.${{ env.Region }}.amazonaws.com/${{ env.name }}:latest


      - name: update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.clustername }}    --region ${{ env.Region }} 

      

      - name: deploy 
        run: kubectl apply -f nginx-deployment-service.yaml

      - name: svc
        run: kubectl get svc
      - name: pod
        run: kubectl get pods

      - name: log
        run: kubectl describe pods nginx-deployment-54dcc97b7b-cmfkl  

        
    



      
      

      
      

      

      

        


      

      
        

        

        

      
